resources:
- name: test-pipeline
  type: git
  source:
    uri: git@github.com:henryaj/test-pipeline.git
    branch: master
    private_key: {{private_key}}

jobs:
- name: test-job
  plan:
  - get: test-pipeline
  - task: test-job
    file: test-pipeline/tasks/test-job.yml
    config:
      image: docker:///cflondonservices/london-services-ci-base#stable
